### ISSUE TITLE
[Bug]: Handle Multiple Connections

### ISSUE THREAD

**Issue by tonysm** [richan-fongdasen/turso-laravel#10]
### What happened?

I have the need to have multiple database connections in the same app, both multiple Turso connections but also non-Turso connections. The package seems to expect (here and here) a single database connection called `turso`. Any specific reason for that? Also, any hints on how I can achieve multiple connections on my own app?

Great work here, and thanks for creating a PingCRM example. 👍🏼 

### How to reproduce the bug

I cloned the PingCRM example, added a new connection called `contacts` that also uses the `turso` driver, and configured both the Contact model to use that connection and the `create_contacts_table` migration. It doesn't seem to have any effect.

### Package Version

0.7.0

### PHP Version

8.3.9

### Laravel Version

11.1.1

**Comment by plunkettscott** [comment]
Just ran into this as well, took me a bit to figure out what was happening as I was not expecting this behavior.

**Comment by richan-fongdasen** [comment]
Hi, I apologize for my delayed response. Could you confirm if the issue has been resolved with the updates in the `multi-connections` branch?

To use the package from the `multi-connections` branch, run this command:
```
composer require "richan-fongdasen/turso-laravel:dev-multi-connections"
```

Note: The `multi-connections` branch includes breaking changes. Please read the readme file in that branch before proceeding.

**Comment by richan-fongdasen** [comment]
I'm closing this issue as it has been fixed in commit https://github.com/richan-fongdasen/turso-laravel/commit/3b446e39ea247760347c1d6324c7c58e0aedc207
