### ISSUE TITLE
[Bug]: Protocol "libsql" not supported 

### ISSUE THREAD

**Issue by wilhelmpa** [richan-fongdasen/turso-laravel#6]
### What happened?

I try to run the migration, but there comes the following error: 

  cURL error 1: Protocol "libsql" not supported (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for libsql://xxx-yyy.turso.io/v3/pipeline (Connection: turso, SQL: select name from sqlite_master where type = 'table' and name not like 'sqlite_%' order by name)
  
  Do you have any ideas?

Besides that, this Project is so awesome, thank you very much

### How to reproduce the bug

run the migration script also with a fresh install of your cms project

### Package Version

I dont know

### PHP Version

8.3

### Laravel Version

11

**Comment by richan-fongdasen** [comment]
Hi @wilhelmpa, thanks for submitting the issue . I think I have an idea about what's going on here. The given Turso database URL is defined using the `libsql://` protocol. The package doesn't currently recognize the `libsql` protocol. A quick fix would be to replace the `libsql` protocol with `https`.

I know this will be confusing for new users, so I will work on making it unnecessary to replace the protocol in the future.

**Comment by wilhelmpa** [comment]
Uh my bad. I just copy pasted from turso instead of reading your docs carefully. It worked! Thank you very much!!!!! So nice

**Comment by richan-fongdasen** [comment]
The issue has been permanently fixed by this commit https://github.com/richan-fongdasen/turso-laravel/commit/0ce0a8bd1116f316d2fd1f11cc0f496320bc67e4
